### ISSUE TITLE
binaries or build instructions?

### ISSUE THREAD

**Issue by RMHogervorst** [videah/plato-opds#1]
I would really like to try your hook, is it possible you provide the binaries too? 
I can't get the toolchain + rust combination to work on my macos machine.

a docker build image would be fine too

**Comment by videah** [comment]
As of 8535c47 I've added [instructions to cross-compile](https://github.com/videah/plato-opds#building) easily with Docker using the tool cross along with some prebuilt binaries on the [release page](https://github.com/videah/plato-opds/releases).

If you have any more issues please let me know!

**Comment by RMHogervorst** [comment]
I am so sorry I missed that!
